# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/ebaz.xdc

# Block Designs: bd/zynq/zynq.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq || ORIG_REF_NAME==zynq} -quiet] -quiet

# IP: bd/zynq/ip/zynq_processing_system7_0_0/zynq_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_processing_system7_0_0 || ORIG_REF_NAME==zynq_processing_system7_0_0} -quiet] -quiet

# IP: bd/zynq/ip/zynq_BEEP_MODULE_0_1/zynq_BEEP_MODULE_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_BEEP_MODULE_0_1 || ORIG_REF_NAME==zynq_BEEP_MODULE_0_1} -quiet] -quiet

# IP: bd/zynq/ip/zynq_xlconcat_0_0/zynq_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_xlconcat_0_0 || ORIG_REF_NAME==zynq_xlconcat_0_0} -quiet] -quiet

# IP: bd/zynq/ip/zynq_xlslice_0_0/zynq_xlslice_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_xlslice_0_0 || ORIG_REF_NAME==zynq_xlslice_0_0} -quiet] -quiet

# IP: bd/zynq/ip/zynq_xlslice_0_3/zynq_xlslice_0_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_xlslice_0_3 || ORIG_REF_NAME==zynq_xlslice_0_3} -quiet] -quiet

# IP: bd/zynq/ip/zynq_xlslice_1_5/zynq_xlslice_1_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_xlslice_1_5 || ORIG_REF_NAME==zynq_xlslice_1_5} -quiet] -quiet

# IP: bd/zynq/ip/zynq_xlslice_1_6/zynq_xlslice_1_6.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_xlslice_1_6 || ORIG_REF_NAME==zynq_xlslice_1_6} -quiet] -quiet

# IP: bd/zynq/ip/zynq_xlslice_1_8/zynq_xlslice_1_8.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_xlslice_1_8 || ORIG_REF_NAME==zynq_xlslice_1_8} -quiet] -quiet

# IP: bd/zynq/ip/zynq_xlslice_1_9/zynq_xlslice_1_9.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_xlslice_1_9 || ORIG_REF_NAME==zynq_xlslice_1_9} -quiet] -quiet

# IP: bd/zynq/ip/zynq_axi_gpio_0_1/zynq_axi_gpio_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_axi_gpio_0_1 || ORIG_REF_NAME==zynq_axi_gpio_0_1} -quiet] -quiet

# IP: bd/zynq/ip/zynq_ps7_0_axi_periph_0/zynq_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_ps7_0_axi_periph_0 || ORIG_REF_NAME==zynq_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/zynq/ip/zynq_rst_ps7_0_50M_0/zynq_rst_ps7_0_50M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_rst_ps7_0_50M_0 || ORIG_REF_NAME==zynq_rst_ps7_0_50M_0} -quiet] -quiet

# IP: bd/zynq/ip/zynq_auto_pc_0/zynq_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_auto_pc_0 || ORIG_REF_NAME==zynq_auto_pc_0} -quiet] -quiet

# XDC: bd/zynq/ip/zynq_processing_system7_0_0/zynq_processing_system7_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==zynq_processing_system7_0_0 || ORIG_REF_NAME==zynq_processing_system7_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/zynq/ip/zynq_axi_gpio_0_1/zynq_axi_gpio_0_1_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==zynq_axi_gpio_0_1 || ORIG_REF_NAME==zynq_axi_gpio_0_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/zynq/ip/zynq_axi_gpio_0_1/zynq_axi_gpio_0_1_ooc.xdc

# XDC: bd/zynq/ip/zynq_axi_gpio_0_1/zynq_axi_gpio_0_1.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==zynq_axi_gpio_0_1 || ORIG_REF_NAME==zynq_axi_gpio_0_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/zynq/ip/zynq_rst_ps7_0_50M_0/zynq_rst_ps7_0_50M_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==zynq_rst_ps7_0_50M_0 || ORIG_REF_NAME==zynq_rst_ps7_0_50M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/zynq/ip/zynq_rst_ps7_0_50M_0/zynq_rst_ps7_0_50M_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==zynq_rst_ps7_0_50M_0 || ORIG_REF_NAME==zynq_rst_ps7_0_50M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/zynq/ip/zynq_rst_ps7_0_50M_0/zynq_rst_ps7_0_50M_0_ooc.xdc

# XDC: bd/zynq/ip/zynq_auto_pc_0/zynq_auto_pc_0_ooc.xdc

# XDC: bd/zynq/zynq_ooc.xdc
